language: r

sudo: required

before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap

addons:
  apt:
    packages:
      - libmagick++-dev

script: ./travis-tool.sh run_tests

after_failure:
- ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: sandovalp.ce@gmail.com
    on_failure: sandovalp.ce@gmail.com
