# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
# https://github.com/craigcitro/r-travis/wiki
language: c

before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap

install:
- ./travis-tool.sh r_binary_install Rcpp gplots reshape2 rgl jsonlite grDevices graphics
- ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
- ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: sandovalp.ce@gmail.com
    on_failure: sandovalp.ce@gmail.com

