language: r
cache: packages
sudo: required

env:
  - RGL_USE_NULL=TRUE

addons:
  apt:
    packages:
      - libmagick++-dev

notifications:
  email:
    on_success: sandovalp.ce@gmail.com
    on_failure: sandovalp.ce@gmail.com
